### ISSUE TITLE
Unhandled Exception after clicking arrows on right

### ISSUE THREAD

**Issue by atla5** [frozen-solid/CSharp_MARC#11]
Clicking on the up or down arrow on the right causes an unhandled 'Index Out of Range' 
  error.

Error occurs regardless of which record id or tag (first, middle, last) is selected, or 
  if more than one record is selected

_Running on 64-bit Windows 7 Enteprise._

#### text:  ####

```
Unhandled exception has occurred in your application. If you click Continue, the application 
  ignore this error and attempt to continue. If you click Quit, the application will close immediately.

Index was out of range. Must be non-negative and less than the size of the collection.

Parameter name: index.
```

#### screenshots: ####
![exception-text-index](https://cloud.githubusercontent.com/assets/5565284/16014434/16bf73c0-315f-11e6-973c-dc17b4571113.PNG)

![error-fullscreen](https://cloud.githubusercontent.com/assets/5565284/16014823/e5c9fdce-3160-11e6-8f2d-661a62320da2.PNG)

#### full details: ####
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.get_Item(Int32 index)
   at System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
   at System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
   at CSharp_MARC_Editor.MainForm.subfieldUpButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1076.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
CSharp_MARC Editor
    Assembly Version: 2016.6.12.1
    Win32 Version: 2016.06.12.1
    CodeBase: file:///C:/Users/akswcs1/Downloads/CSharp.MARC.Editor/CSharp_MARC%20Editor.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1075.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1068.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
```

**Comment by frozen-solid** [comment]
Fixed in commit d6eb34d - will be in the next release
