### ISSUE TITLE
Critical Fail

### ISSUE THREAD

**Issue by Amourspirit** [frozen-solid/CSharp_MARC#13]
I was putting in my first record. Attempted to put in 035 of the record below.  I got an error so I tried to skip to 040 by renaming 035 to 040 and got another or the same error not sure.

Now each time I open the app I get Unhanded Exception. If I ignore the app is just frozen. The only other option is to quit. I broke you app in my first 10 minutes. I guessing I need to delete or edit the database to reset. Can you please help.

The Record below comes from https://calgary.bibliocommons.com/item/show/642846095?active_tab=bib_info
-> Full Record -> Mark display
I would love to have a way to import or paste such records into CSharp_MARC.

000 	  	$aam a0n a
001 	  	$acpl01015429
003 	  	$aDLC
005 	  	$a20100805103101.0
008 	  	$a100805s2010 nyua b 001 0 eng d
020 	  	$a9781583333938 (pbk.)
035 	  	$a(OCoLC)462901951
040 	  	$aDLC$cDLC
042 	  	$apcc
082 	00 	$a616.6/5$222
099 	  	$a616. 65 SCA 2010
100 	1 	$aScardino, Peter T.
245 	10 	$aDr. Peter Scardino's prostate book :$bthe complete guide to overcoming prostate cancer, prostatitis, and BPH /$cPeter T. Scardino and Judith Kelman.
246 	10 	$aProstate book
250 	  	$a2nd ed.
260 	  	$aNew York :$bAvery,$c2010.
300 	  	$axxvi, 565 p. :$bill.
504 	  	$aIncludes bibliographical references and index.
596 	  	$a6 15
650 	 0 	$aProstate$vPopular works.
700 	1 	$aKelman, Judith.

__________________________________________________
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CSharp_MARC_Editor.MainForm.LoadPreview(Int32 recordID, Boolean recordsTableReload)
   at CSharp_MARC_Editor.MainForm.LoadFields(Int32 recordID)
   at CSharp_MARC_Editor.MainForm.loadingBackgroundWorker_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
CSharp_MARC Editor
    Assembly Version: 2018.2.20.0
    Win32 Version: 2018.02.20.0
    CodeBase: file:///C:/Users/bigby/AppData/Local/Apps/2.0/AZL5JT02.8R7/E1ZX6RRO.VW4/csha..tion_9e24aae7a729629d_07e2.0002_5501cb4bd75a0916/CSharp_MARC%20Editor.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Data.DataSetExtensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.DataSetExtensions/v4.0_4.0.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.107.0
    Win32 Version: 1.0.107.0
    CodeBase: file:///C:/Users/bigby/AppData/Local/Apps/2.0/AZL5JT02.8R7/E1ZX6RRO.VW4/csha..tion_9e24aae7a729629d_07e2.0002_5501cb4bd75a0916/System.Data.SQLite.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
CSharp_MARC
    Assembly Version: 2018.2.20.0
    Win32 Version: 2018.02.20.0
    CodeBase: file:///C:/Users/bigby/AppData/Local/Apps/2.0/AZL5JT02.8R7/E1ZX6RRO.VW4/csha..tion_9e24aae7a729629d_07e2.0002_5501cb4bd75a0916/CSharp_MARC.DLL
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by frozen-solid** [comment]
You can reset the database by deleting the MARC.db file in the application directory. It will recreate it the first time you load the application.

If you installed it using the installer exe the process is a little more difficult. You have to go to c:\users\your username\AppData\Local\Apps\2.0\[there should be a folder here named random characters]

Inside that folder should be a bunch of other folders. Sort by date modified and open the newest folder. It should have a MARC.db file in it that you can delete.

As for the error, I'll see if I can figure out how to duplicate your crash. If you reset the database and continue to have problems, let me know what steps you're taking to cause the crash and I'll be able to fix it.

Thanks

-Mattie
